package com.example.sourcewebteam.entity;

public class TFavorites extends baseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorites.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorites.user_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_favorites.post_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Long postId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.id
     *
     * @return the value of t_favorites.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.id
     *
     * @param id the value for t_favorites.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.user_id
     *
     * @return the value of t_favorites.user_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.user_id
     *
     * @param userId the value for t_favorites.user_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_favorites.post_id
     *
     * @return the value of t_favorites.post_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_favorites.post_id
     *
     * @param postId the value for t_favorites.post_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }
}