package com.example.sourcewebteam.entity;

import java.util.Date;

public class THistory extends baseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.user_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.post_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.view_date
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Date viewDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.id
     *
     * @return the value of t_history.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.id
     *
     * @param id the value for t_history.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.user_id
     *
     * @return the value of t_history.user_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.user_id
     *
     * @param userId the value for t_history.user_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.post_id
     *
     * @return the value of t_history.post_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.post_id
     *
     * @param postId the value for t_history.post_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.view_date
     *
     * @return the value of t_history.view_date
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Date getViewDate() {
        return viewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.view_date
     *
     * @param viewDate the value for t_history.view_date
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setViewDate(Date viewDate) {
        this.viewDate = viewDate;
    }
}