package com.example.sourcewebteam.entity;

import java.util.Date;

public class THistory extends baseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.user_id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.post_id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    private Long postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_history.view_date
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    private Date viewDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.id
     *
     * @return the value of t_history.id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.id
     *
     * @param id the value for t_history.id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.user_id
     *
     * @return the value of t_history.user_id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.user_id
     *
     * @param userId the value for t_history.user_id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.post_id
     *
     * @return the value of t_history.post_id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public Long getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.post_id
     *
     * @param postId the value for t_history.post_id
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_history.view_date
     *
     * @return the value of t_history.view_date
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public Date getViewDate() {
        return viewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_history.view_date
     *
     * @param viewDate the value for t_history.view_date
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    public void setViewDate(Date viewDate) {
        this.viewDate = viewDate;
    }
}