package com.example.sourcewebteam.entity;

import java.util.Date;

public class TNotification extends baseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.notifier
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.receiver
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.create_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.content
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notification.status
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.id
     *
     * @return the value of t_notification.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.id
     *
     * @param id the value for t_notification.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.notifier
     *
     * @return the value of t_notification.notifier
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.notifier
     *
     * @param notifier the value for t_notification.notifier
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.receiver
     *
     * @return the value of t_notification.receiver
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.receiver
     *
     * @param receiver the value for t_notification.receiver
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.create_time
     *
     * @return the value of t_notification.create_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.create_time
     *
     * @param createTime the value for t_notification.create_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.content
     *
     * @return the value of t_notification.content
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.content
     *
     * @param content the value for t_notification.content
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notification.status
     *
     * @return the value of t_notification.status
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notification.status
     *
     * @param status the value for t_notification.status
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}