package com.example.sourcewebteam.entity;

import java.util.Date;

public class TPost extends baseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.title
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.content
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.tag
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.image
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.video
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.type
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.is_deleted
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.creator_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.hits
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer hits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.favorites
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer favorites;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.create_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.modified_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Date modifiedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.agree
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer agree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.disagree
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private Integer disagree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.summary
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    private String summary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.id
     *
     * @return the value of t_post.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.id
     *
     * @param id the value for t_post.id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.title
     *
     * @return the value of t_post.title
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.title
     *
     * @param title the value for t_post.title
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.content
     *
     * @return the value of t_post.content
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.content
     *
     * @param content the value for t_post.content
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.tag
     *
     * @return the value of t_post.tag
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.tag
     *
     * @param tag the value for t_post.tag
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.image
     *
     * @return the value of t_post.image
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.image
     *
     * @param image the value for t_post.image
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.video
     *
     * @return the value of t_post.video
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.video
     *
     * @param video the value for t_post.video
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setVideo(String video) {
        this.video = video == null ? null : video.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.type
     *
     * @return the value of t_post.type
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.type
     *
     * @param type the value for t_post.type
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.is_deleted
     *
     * @return the value of t_post.is_deleted
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.is_deleted
     *
     * @param isDeleted the value for t_post.is_deleted
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.creator_id
     *
     * @return the value of t_post.creator_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.creator_id
     *
     * @param creatorId the value for t_post.creator_id
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.hits
     *
     * @return the value of t_post.hits
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getHits() {
        return hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.hits
     *
     * @param hits the value for t_post.hits
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setHits(Integer hits) {
        this.hits = hits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.favorites
     *
     * @return the value of t_post.favorites
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getFavorites() {
        return favorites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.favorites
     *
     * @param favorites the value for t_post.favorites
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setFavorites(Integer favorites) {
        this.favorites = favorites;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.create_time
     *
     * @return the value of t_post.create_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.create_time
     *
     * @param createTime the value for t_post.create_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.modified_time
     *
     * @return the value of t_post.modified_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.modified_time
     *
     * @param modifiedTime the value for t_post.modified_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.agree
     *
     * @return the value of t_post.agree
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getAgree() { return agree; }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.modified_time
     *
     * @param agree the value for t_post.agree
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setAgree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.disagree
     *
     * @return the value of t_post.disagree
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public Integer getDisagree() {
        return disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.disagree
     *
     * @param disagree the value for t_post.modified_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setDisagree(Integer disagree) {
        this.disagree = disagree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.summary
     *
     * @return the value of t_post.summary
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.summary
     *
     * @param summary the value for t_post.modified_time
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

}