package com.example.sourcewebteam.mapper;

import com.example.sourcewebteam.entity.TComment;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Delete({
        "delete from t_comment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Insert({
        "insert into t_comment (id, parent_id, ",
        "commentator, create_time, ",
        "modified_time, likes, ",
        "content, comment_count)",
        "values (#{id,jdbcType=BIGINT}, #{parentId,jdbcType=BIGINT}, ",
        "#{commentator,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifiedTime,jdbcType=TIMESTAMP}, #{likes,jdbcType=BIGINT}, ",
        "#{content,jdbcType=VARCHAR}, #{commentCount,jdbcType=BIGINT})"
    })
    int insert(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Select({
        "select",
        "id, parent_id, commentator, create_time, modified_time, likes, content, comment_count",
        "from t_comment",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.BIGINT),
        @Result(column="commentator", property="commentator", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_time", property="modifiedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="likes", property="likes", jdbcType=JdbcType.BIGINT),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="comment_count", property="commentCount", jdbcType=JdbcType.BIGINT)
    })
    TComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Select({
        "select",
        "id, parent_id, commentator, create_time, modified_time, likes, content, comment_count",
        "from t_comment",
        "order by id"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="parent_id", property="parentId", jdbcType=JdbcType.BIGINT),
        @Result(column="commentator", property="commentator", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_time", property="modifiedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="likes", property="likes", jdbcType=JdbcType.BIGINT),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="comment_count", property="commentCount", jdbcType=JdbcType.BIGINT)
    })
    List<TComment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Update({
        "update t_comment",
        "set parent_id = #{parentId,jdbcType=BIGINT},",
          "commentator = #{commentator,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP},",
          "likes = #{likes,jdbcType=BIGINT},",
          "content = #{content,jdbcType=VARCHAR},",
          "comment_count = #{commentCount,jdbcType=BIGINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TComment record);
}