package com.example.sourcewebteam.mapper;

import com.example.sourcewebteam.entity.THistory;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface THistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Delete({
        "delete from t_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Insert({
        "insert into t_history (id, user_id, ",
        "post_id, view_date)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{postId,jdbcType=INTEGER}, #{viewDate,jdbcType=TIMESTAMP})"
    })
    int insert(THistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Select({
        "select",
        "id, user_id, post_id, view_date",
        "from t_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="post_id", property="postId", jdbcType=JdbcType.INTEGER),
        @Result(column="view_date", property="viewDate", jdbcType=JdbcType.TIMESTAMP)
    })
    THistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Select({
        "select",
        "id, user_id, post_id, view_date",
        "from t_history",
        "order by view_date"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="post_id", property="postId", jdbcType=JdbcType.INTEGER),
        @Result(column="view_date", property="viewDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<THistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_history
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Update({
        "update t_history",
        "set user_id = #{userId,jdbcType=INTEGER},",
          "post_id = #{postId,jdbcType=INTEGER},",
          "view_date = #{viewDate,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(THistory record);
}