package com.example.sourcewebteam.mapper;

import com.example.sourcewebteam.entity.TNotification;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    @Delete({
        "delete from t_notification",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    @Insert({
        "insert into t_notification (id, notifier, ",
        "receiver, create_time, ",
        "content, status)",
        "values (#{id,jdbcType=BIGINT}, #{notifier,jdbcType=BIGINT}, ",
        "#{receiver,jdbcType=BIGINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{content,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER})"
    })
    int insert(TNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    @Select({
        "select",
        "id, notifier, receiver, create_time, content, status",
        "from t_notification",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="notifier", property="notifier", jdbcType=JdbcType.BIGINT),
        @Result(column="receiver", property="receiver", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    TNotification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    @Select({
        "select",
        "id, notifier, receiver, create_time, content, status",
        "from t_notification",
        "order by id"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="notifier", property="notifier", jdbcType=JdbcType.BIGINT),
        @Result(column="receiver", property="receiver", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.INTEGER)
    })
    List<TNotification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notification
     *
     * @mbg.generated Tue Feb 15 23:20:39 CST 2022
     */
    @Update({
        "update t_notification",
        "set notifier = #{notifier,jdbcType=BIGINT},",
          "receiver = #{receiver,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "content = #{content,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TNotification record);
}