package com.example.sourcewebteam.mapper;

import com.example.sourcewebteam.entity.TPost;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Delete({
        "delete from t_post",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Insert({
        "insert into t_post (id, title, ",
        "content, tag, image, ",
        "video, type, is_deleted, ",
        "creator_id, hits, favorites, ",
        "create_time, modified_time, ",
        "agree, disagree, summary)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{content,jdbcType=VARCHAR}, #{tag,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR}, ",
        "#{video,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, #{isDeleted,jdbcType=INTEGER}, ",
        "#{creatorId,jdbcType=INTEGER}, #{hits,jdbcType=INTEGER}, #{favorites,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifiedTime,jdbcType=TIMESTAMP}, #{agree,jdbcType=INTEGER}, ",
        "#{disagree,jdbcType=INTEGER}, #{summary,jdbcType=VARCHAR})"
    })
    int insert(TPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Select({
        "select",
        "id, title, content, tag, image, video, type, is_deleted, creator_id, hits, favorites, ",
        "create_time, modified_time, agree, disagree, summary",
        "from t_post",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="tag", property="tag", jdbcType=JdbcType.VARCHAR),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="video", property="video", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.INTEGER),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.INTEGER),
        @Result(column="hits", property="hits", jdbcType=JdbcType.INTEGER),
        @Result(column="favorites", property="favorites", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_time", property="modifiedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="agree", property="agree", jdbcType=JdbcType.INTEGER),
        @Result(column="disagree", property="disagree", jdbcType=JdbcType.INTEGER),
        @Result(column="summary", property="summary", jdbcType=JdbcType.INTEGER)
    })
    TPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Select({
        "select",
        "id, title, content, tag, image, video, type, is_deleted, creator_id, hits, favorites, ",
        "create_time, modified_time, agree, disagree, summary",
        "from t_post",
        "order by id"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="tag", property="tag", jdbcType=JdbcType.VARCHAR),
        @Result(column="image", property="image", jdbcType=JdbcType.VARCHAR),
        @Result(column="video", property="video", jdbcType=JdbcType.VARCHAR),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.INTEGER),
        @Result(column="creator_id", property="creatorId", jdbcType=JdbcType.INTEGER),
        @Result(column="hits", property="hits", jdbcType=JdbcType.INTEGER),
        @Result(column="favorites", property="favorites", jdbcType=JdbcType.INTEGER),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="modified_time", property="modifiedTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="agree", property="agree", jdbcType=JdbcType.INTEGER),
        @Result(column="disagree", property="disagree", jdbcType=JdbcType.INTEGER),
        @Result(column="summary", property="summary", jdbcType=JdbcType.INTEGER)
    })
    List<TPost> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbg.generated Wed Feb 16 20:53:31 CST 2022
     */
    @Update({
        "update t_post",
        "set title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "tag = #{tag,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "video = #{video,jdbcType=VARCHAR},",
          "type = #{type,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=INTEGER},",
          "creator_id = #{creatorId,jdbcType=INTEGER},",
          "hits = #{hits,jdbcType=INTEGER},",
          "favorites = #{favorites,jdbcType=INTEGER},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "modified_time = #{modifiedTime,jdbcType=TIMESTAMP}",
          "#{agree,jdbcType=INTEGER}, ",
          "#{disagree,jdbcType=INTEGER},",
          "#{summary,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPost record);

    @Update({
        "update t_post",
        "set agree = #{agree,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateAgreeById(int id, int agree);

    @Select("select agree from t_post where id = #{id,jdbcType=INTEGER}")
    int selectAgreeById(int id);

    @Select("select * from t_post limit #{offset}, #{size}")
    List<TPost> list(Integer offset, Integer size);

    @Select("select count(1) from t_post")
    Integer count();

}